config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {
  sessions: 'admin/sessions'
}
  devise_for :users, :controllers => {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  get 'homes/top'
  root to: "homes#top"
  
 
  
  scope module: :public do
    resources :follows, only: [:followers, :followings]
    resources :questions, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
       resources :question_comments, only: [:create, :destroy]
       
    end
    resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
       resources :post_comments, only: [:create, :destroy]
       resource :favorites, only: [:create, :destroy]
       
    end
    resources :users, only: [:index, :show, :edit, :update, :unsubscribe] do
      resource :follows, only: [:create, :destroy]
      get 'followings' => 'follows#followings', as: 'followings'
      get 'followers' => 'follows#followers', as: 'followers'
      member do
        get :favorites
     end  
     
    end  
    
      # 退会確認画面
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
     # 論理削除用のルーティング
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    
    
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gardener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'ユーザー一覧', users_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '画像投稿', new_post_image_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '画像一覧', post_images_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '質問投稿', new_question_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '質問一覧', questions_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to 'ユーザー一覧', users_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '画像一覧', post_images_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '質問一覧', questions_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li>
              <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, method: :post , class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item"> 
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
  </body>
</html>